resolver: lts-20.26
packages:
- .
extra-deps:
- amazonka-2.0
- amazonka-core-2.0
- amazonka-rds-2.0
- amazonka-sso-2.0
- amazonka-sts-2.0
- co-log-0.5.0.0
- chronos-1.1.5
- crypton-0.33
- git: https://codeberg.org/aka_dude/effectful-zoo
  commit: 376e83aeee9a0c927eb17499c7b82adc1e8d080c
  # nix-sha256: 00sbzpjxa451i58ssjg1yvvcbfw9vifj9h1670n7sn4ifxcvnj0x
  subdirs:
  - effectful-co-log
- typerep-map-0.5.0.0
