name: Deployment
on:
  workflow_call:
    inputs:
      target_repository:
        description: Repository with NixOS configuration
        type: string
        required: true
      target_ref:
        description: Target repository's ref
        type: string
        default: main
        required: false
    secrets:
      MY_SSH_KEY:
        required: true
      DEVOPS_SSH_KEY:
        required: true
jobs:
  request-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            extra-substituters = https://cache.iog.io https://iohk.cachix.org
            extra-trusted-public-keys = cache.iog.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo=
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.target_repository }}
          ref: ${{ inputs.target_ref }}
          ssh-key: ${{ secrets.DEVOPS_SSH_KEY }}
          ssh-strict: true
      - name: Request deployment
        shell: bash
        env:
          MY_SSH_KEY: ${{ secrets.MY_SSH_KEY }}
          DEVOPS_SSH_KEY: ${{ secrets.DEVOPS_SSH_KEY }}
        run: |
          branch_re='^deploy/(.*)$'

          function on_re_mismatch {
            # non-standard branches are prohibited
            echo "ERROR: $GITHUB_REF_NAME does not match 'deploy/*' format";
            exit 1
          }

          umask 077
          mkdir ~/.ssh
          echo "$MY_SSH_KEY" > ~/.ssh/my

          set -x

          cat << EOF > ~/.ssh/config
          Host github.com*
            IdentityFile ~/.ssh/my
            Hostname github.com
          EOF

          [[ $GITHUB_REF_NAME =~ $branch_re ]] \
            && dependency=${BASH_REMATCH[1]} \
            || on_re_mismatch

          # nix shell github:dev-osmos/memento/${{ github.action_ref }} -c mto config update $dependency
          curl https://github.com/dev-osmos/memento/releases/download/v0.1.0/memento_v0.1.0_amd64.deb > memento.deb
          dpkg -i memento.deb
          mto config update $dependency

          git config user.email github-actions@github.com
          git config user.name "Github Actions"

          git add .
          git commit -m "Autoupdate $dependency"
          git push

          echo "Deployment successfully requested!"
